
export const herosInfo = {
    '*Alpha*':          { name: '알파' , image: 'alpha.png' },
    '*Ardan*':          { name: '아단' , image: 'ardan.png' },
    '*Baptiste*':       { name: '바티스트' , image: 'baptiste.png' },
    '*Baron*':          { name: '바론' , image: 'baron.png' },
    '*Blackfeather*':   { name: '흑깃' , image: 'blackfeather.png' },
    '*Catherine*':      { name: '캐서린' , image: 'catherine.png' },
    '*Celeste*':        { name: '셀레스트' , image: 'celeste.png' },
    '*Churnwalker*':    { name: '어둠추적자' , image: 'churnwalker.png' },
    '*Flicker*':        { name: '플리커' , image: 'flicker.png' },
    '*Fortress*':       { name: '포트리스' , image: 'fortress.png' },
    '*Glaive*':         { name: '글레이브' , image: 'glaive.png' },
    '*Grace*':          { name: '그레이스' , image: 'grace.png' },
    '*Grumpjaw*':       { name: '사슬니' , image: 'grumpjaw.png' },
    '*Gwen*':           { name: '그웬' , image: 'gwen.png' },
    '*Idris*':          { name: '이드리스' , image: 'idris.png' },
    '*Kestrel*':        { name: '케스트럴' , image: 'kestrel.png' },
    '*Koshka*':         { name: '코쉬카' , image: 'koshka.png' },
    '*Krul*':           { name: '크럴' , image: 'krul.png' },
    '*Lance*':          { name: '랜스' , image: 'lance.png' },
    '*Lorelai*':        { name: '로레라이' , image: 'lorelai.png' },
    '*Lyra*':           { name: '라이라' , image: 'lyra.png' },
    '*Ozo*':            { name: '오조' , image: 'ozo.png' },
    '*Petal*':          { name: '페탈' , image: 'petal.png' },
    '*Phinn*':          { name: '핀' , image: 'phinn.png' },
    '*Reim*':           { name: '레임' , image: 'reim.png' },
    '*Reza*':           { name: '레자' , image: 'reza.png' },
    '*Ringo*':          { name: '링고' , image: 'ringo.png' },
    '*Rona*':           { name: '로나' , image: 'rona.png' },
    '*Samuel*':         { name: '사무엘' , image: 'samuel.png' },
    '*Saw*':            { name: '쏘우' , image: 'saw.png' },
    '*Skaarf*':         { name: '스카프' , image: 'skaarf.png' },
    '*Skye*':           { name: '스카이' , image: 'skye.png' },
    '*Taka*':           { name: '타카' , image: 'taka.png' },
    '*Varya*':          { name: '바이라' , image: 'varya.png' },
    '*Vox*':            { name: '복스' , image: 'vox.png' },
};