
export const heroInfo = {
    '*Alpha*':          { name: '알파' , image: 'alpha.png' },
    '*Ardan*':          { name: '아단' , image: 'ardan.png' },
    '*Baptiste*':       { name: '바티스트' , image: 'baptiste.png' },
    '*Baron*':          { name: '바론' , image: 'baron.png' },
    '*Blackfeather*':   { name: '흑깃' , image: 'blackfeather.png' },
    '*Catherine*':      { name: '캐서린' , image: 'catherine.png' },
    '*Celeste*':        { name: '셀레스트' , image: 'celeste.png' },
    '*Churnwalker*':    { name: '어둠추적자' , image: 'churnwalker.png' },
    '*Flicker*':        { name: '플리커' , image: 'flicker.png' },
    '*Fortress*':       { name: '포트리스' , image: 'fortress.png' },
    '*Glaive*':         { name: '글레이브' , image: 'glaive.png' },
    '*Grace*': { name: '그레이스' , image: 'grace.png' },
    '*Grumpjaw*': { name: '사슬니' , image: 'grumpjaw.png' },
    '*Gwen*': { name: '그웬' , image: 'gwen.png' },
    '*Idris*': { name: '이드리스' , image: 'idris.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
    '*Ardan*': { name: '아단' , image: 'ardan.png' },
};