
export const herosInfo = {
    '*Adagio*':          { name: '아다지오' , image: 'adagio.png' },
    '*Alpha*':          { name: '알파' , image: 'alpha.png' },
    '*Ardan*':          { name: '아단' , image: 'ardan.png' },
    '*Baptiste*':       { name: '바티스트' , image: 'baptiste.png' },
    '*Baron*':          { name: '바론' , image: 'baron.png' },
    '*Blackfeather*':   { name: '흑깃' , image: 'blackfeather.png' },
    '*Catherine*':      { name: '캐서린' , image: 'catherine.png' },
    '*Celeste*':        { name: '셀레스트' , image: 'celeste.png' },
    '*Churnwalker*':    { name: '어둠추적자' , image: 'churnwalker.png' },
    '*Flicker*':        { name: '플리커' , image: 'flicker.png' },
    '*Fortress*':       { name: '포트리스' , image: 'fortress.png' },
    '*Glaive*':         { name: '글레이브' , image: 'glaive.png' },
    '*Grace*':          { name: '그레이스' , image: 'grace.png' },
    '*Grumpjaw*':       { name: '사슬니' , image: 'grumpjaw.png' },
    '*Gwen*':           { name: '그웬' , image: 'gwen.png' },
    '*Idris*':          { name: '이드리스' , image: 'idris.png' },
    '*Joule*':          { name: '쥴' , image: 'joule.png' },
    '*Kestrel*':        { name: '케스트럴' , image: 'kestrel.png' },
    '*Koshka*':         { name: '코쉬카' , image: 'koshka.png' },
    '*Krul*':           { name: '크럴' , image: 'krul.png' },
    '*Lance*':          { name: '랜스' , image: 'lance.png' },
    '*Lorelai*':        { name: '로레라이' , image: 'lorelai.png' },
    '*Lyra*':           { name: '라이라' , image: 'lyra.png' },
    '*Ozo*':            { name: '오조' , image: 'ozo.png' },
    '*Petal*':          { name: '페탈' , image: 'petal.png' },
    '*Phinn*':          { name: '핀' , image: 'phinn.png' },
    '*Reim*':           { name: '레임' , image: 'reim.png' },
    '*Reza*':           { name: '레자' , image: 'reza.png' },
    '*Ringo*':          { name: '링고' , image: 'ringo.png' },
    '*Rona*':           { name: '로나' , image: 'rona.png' },
    '*Samuel*':         { name: '사무엘' , image: 'samuel.png' },
    '*SAW*':            { name: '쏘우' , image: 'saw.png' },
    '*Skaarf*':         { name: '스카프' , image: 'skaarf.png' },
    '*Skye*':           { name: '스카이' , image: 'skye.png' },
    '*Taka*':           { name: '타카' , image: 'taka.png' },
    '*Tony*':           { name: '토니' , image: 'tony.png' },
    '*Varya*':          { name: '바이라' , image: 'varya.png' },
    '*Vox*':            { name: '복스' , image: 'vox.png' },
};

export const itemsInfo = {
    'Aegis':                { name: '이지스', image: 'aegis.png' },
    'Aftershock':           { name: '이지스', image: 'aftershock.png' },
    'Alternating Current':  { name: '이지스', image: 'alternating-current.png' },
    'Atlas Pauldron':       { name: '이지스', image: 'atlas-pauldron.png' },
    'Barbed Needle':        { name: '이지스', image: 'barbed-needle.png' },
    'Blazing Salvo':        { name: '이지스', image: 'blazing-salvo.png' },
    'BoneSaw':              { name: '이지스', image: 'bonesaw.png' },
    'Book Of Eulogies':     { name: '이지스', image: 'book-of-eulogies.png' },
    'Breaking Point':       { name: '이지스', image: 'breaking-point.png' },
    'Broken Myth':          { name: '이지스', image: 'broken-myth.png' },
    'Chronograph':          { name: '이지스', image: 'chronograph.png' },
    'Clockwork':            { name: '이지스', image: 'clockwork.png' },
    'Coat Of Plates':       { name: '이지스', image: 'coat-of-plates.png' },
    'Crucible':             { name: '이지스', image: 'crucible.png' },
    'Crystal Bit':          { name: '이지스', image: 'crystal-bit.png' },
    'Crystal Infusion':     { name: '이지스', image: 'crystal-infusion.png' },
    'Dragonblood Contract': { name: '이지스', image: 'dragonblood-contract.png' },
    'Dragonheart':          { name: '이지스', image: 'dragonheart.png' },
    'Dragon Eye':           { name: '이지스', image: 'dragons-eye.png' },
    'Echo':                 { name: '이지스', image: 'echo.png' },
    'Eclipse Prism':        { name: '이지스', image: 'eclipse-prism.png' },
    'Energy Battery':       { name: '이지스', image: 'energy-battery.png' },
    'Eve Of Harvest':       { name: '이지스', image: 'eve-of-harvest.png' },
    'Flare Loader':         { name: '이지스', image: 'flare-loader.png' },
    'Fountain Of Renewal':  { name: '이지스', image: 'fountain-of-renewal.png' },
    'Frostburn':            { name: '이지스', image: 'frostburn.png' },
    'Halcyon Chargers':     { name: '이지스', image: 'halcyon-chargers.png' },
    'Healing Flask':        { name: '이지스', image: 'healing-flask.png' },
    'Heavy Prism':          { name: '이지스', image: 'heavy-prism.png' },
    'Heavy Steel':          { name: '이지스', image: 'heavy-steel.png' },
    'Hourglass':            { name: '이지스', image: 'hourglass.png' },
    'Ironguard Contract':   { name: '이지스', image: 'ironguard-contract.png' },
    'Journey Boots':        { name: '이지스', image: 'journey-boots.png' },
    'Kinetic Shield':       { name: '이지스', image: 'kinetic-shield.png' },
    'Lifespring':           { name: '이지스', image: 'lifespring.png' },
    'Light Armor':          { name: '이지스', image: 'light-armor.png' },
    'Light Shield':         { name: '이지스', image: 'light-shield.png' },
    'Lucky Strike':         { name: '이지스', image: 'lucky-strike.png' },
    'Metal Jacket':         { name: '이지스', image: 'metal-jacket.png' },
    'Minion Candy':         { name: '이지스', image: 'minion-candy.png' },
    'Minions Foot':         { name: '이지스', image: 'minions-foot.png' },
    'Nullwave Gauntlet':    { name: '이지스', image: 'nullwave-gauntlet.png' },
    'Oakheart':             { name: '이지스', image: 'oakheart.png' },
    'Piercing Shard':       { name: '이지스', image: 'piercing-shard.png' },
    'Piercing Spear':       { name: '이지스', image: 'piercing-spear.png' },
    'Poisoned Shiv':        { name: '이지스', image: 'poisoned-shiv.png' },
    'Protector Contract':   { name: '이지스', image: 'protector-contract.png' },
    'Reflex Block':         { name: '이지스', image: 'reflex-block.png' },
    'Scoutpak':             { name: '이지스', image: 'scoutpak.png' },
    'Scouttuff':            { name: '이지스', image: 'scouttuff.png' },
    'Serpent Mask':         { name: '이지스', image: 'serpent-mask.png' },
    'Shatterglass':         { name: '이지스', image: 'shatterglass.png' },
    'Shiversteel':          { name: '이지스', image: 'shiversteel.png' },
    'Six Sins':             { name: '이지스', image: 'six-sins.png' },
    'Slumbering Husk':      { name: '이지스', image: 'slumbering-husk.png' },
    'Sorrowblade':          { name: '이지스', image: 'sorrowblade.png' },
    'Spellfire':            { name: '이지스', image: 'spellfire.png' },
    'Spellsword':           { name: '이지스', image: 'spellsword.png' },
    'Sprint Boots':         { name: '이지스', image: 'sprint-boots.png' },
    'Stormcrown':           { name: '이지스', image: 'stormcrown.png' },
    'Stormguard Banner':    { name: '이지스', image: 'stormguard-banner.png' },
    'Superscout':           { name: '이지스', image: 'superscout.png' },
    'Swift Shooter':        { name: '이지스', image: 'swift-shooter.png' },
    'Teleport Boots':       { name: '이지스', image: 'teleport-boots.png' },
    'Tension Bow':          { name: '이지스', image: 'tension-bow.png' },
    'Tornado Trigger':      { name: '이지스', image: 'tornado-trigger.png' },
    'Travel Boots':         { name: '이지스', image: 'travel-boots.png' },
    'Tyrants Monocle':      { name: '이지스', image: 'tyrants-monocle.png' },
    'Void Battery':         { name: '이지스', image: 'void-battery.png' },
    'War Treads':           { name: '이지스', image: 'war-treads.png' },
    'Weapon Blade':         { name: '이지스', image: 'weapon-blade.png' },
};